### PR TITLE
Update to use an escript and rebar3 + others

### PR DESCRIPTION
**Pull request by djnym**
I went ahead and added in other commits which seemed useful.  I believe it includes the other open pull requests, so those can be closed if this is merged.  I got rid of the shell script and replaced it with an escript generated by rebar3.  This is super convenient as you can just copy it to your path and use it (similar to rebar3 and relx).  I made it version 0.3.0 so if you merge, please tag so I can include it.  I've successfully included this version (along with cecho 0.5.1) in a release so that part all works now.  @mazenharake if you have a chance please take a look.

### CODE REVIEW

**Comment by mazenharake** [comment]
Thank you putting everything together. I'll take a look at everything this weekend!

**Comment by djnym** [comment]
Thanks, not sure why entop is conflicted and it's not an auto merge, I remove the entop script?  Dunno, thanks for taking a look.

**Comment by djnym** [comment]
@mazenharake did you have a chance to check these changes out yet?

**Comment by mazenharake** [comment]
Hi,

I played around with it this evening. I looked through the code which seems fine. Thanks for that. However when trying the `./rebar3 escriptize` command it seems to go through but running:

`(19.3)mazen@Green ~/Dev/entop $ ./_build/default/bin/entop foo@Green HQREOBANGMCTSVQSDGAZ`

Gives me this error:

`=INFO REPORT==== 25-Jun-2017::23:48:50 ===
    application: cecho
    exited: {{driver_error,"cannot open shared object file: Not a directory"},
             {cecho,start,[normal,[]]}}
    type: temporary`

Seems `cecho` didn't compile properly. I tried compiling it again using `./rebar compile` in the `_build/default/lib/cecho` directory and that went better... (at least the helloworld program ran properly). Cecho does produce warnings though so I'll check out what they are tomorrow.

Have any idea on what that could be? I assume you tried this and that it went well on your system?

**Comment by djnym** [comment]
I've not seen that, everything works on my system.  Was there a compile line for cecho?  Here's what my session looked like.
```
molinaro@centos65:7> ./rebar3 escriptize
===> Verifying dependencies...
===> Fetching cecho ({git,"https://github.com/mazenharake/cecho.git",
                                 {ref,"7a0042b930ba64a1d3e496bd29a27ff0b356435f"}})
===> Compiling cecho
make: Entering directory `/mnt/molinaro/projects/thirdparty/entop/_build/default/lib/cecho/c_src'
cc -g -O3 -funroll-loops -I/opt/include -I/usr/local/include -fPIC -I /usr/lib64/erlang/erts-7.3/include/ -I /usr/lib64/erlang/lib/erl_interface-3.8.2/include -I/opt/include -I/usr/local/include -c -o /mnt/molinaro/projects/thirdparty/entop/_build/default/lib/cecho/c_src/cecho.o /mnt/molinaro/projects/thirdparty/entop/_build/default/lib/cecho/c_src/cecho.c
cc /mnt/molinaro/projects/thirdparty/entop/_build/default/lib/cecho/c_src/cecho.o -L/usr/local/lib -L/opt/lib -shared -L /usr/lib64/erlang/lib/erl_interface-3.8.2/lib -lerl_interface -lei -lncurses -o /mnt/molinaro/projects/thirdparty/entop/_build/default/lib/cecho/c_src/../priv/cecho.so
make: Leaving directory `/mnt/molinaro/projects/thirdparty/entop/_build/default/lib/cecho/c_src'
===> Compiling entop
===> Building escript...
```

**Comment by mazenharake** [comment]
I see... But did you try to run the actual entop script that was generated?

**Comment by mazenharake** [comment]
It turns out that the path to where the cecho driver is (the priv dir) gets messed up when running `./rebar3 escriptize`.

I'll have another look tomorrow to see how to fix that, otherwise I'll reinstate the script until we have a solution.

I also realized today that the changes we are trying to pull in were in a different license. I'm not sure how that is treated when taking them in under a new license... I'll have to check it out.

**Comment by djnym** [comment]
Sorry, yes I did and it works fine for me.

**Comment by djnym** [comment]
Oh, I figured out that I also had cecho installed in my erlang system library path, so I was picking up that version and not the version in the escript.  I'll see if I can't figure out what's happening.  It does work when I include it inside a release and invoke it via a shell script so that still works at least.

**Comment by djnym** [comment]
Hmm, this may not work, I found
http://lists.basho.com/pipermail/rebar_lists.basho.com/2012-September/001707.html
which seems to suggest you can't use a .so in an archive, so this may not work as an escript :(

**Comment by djnym** [comment]
@mazenharake I put back a slightly modified version of the bash script.  It should run from within the project, and can be copied out and run as well (assuming you've also installed cecho and entop libs into your erl libs directory).

I simplified the calling, you are no longer required to give a name (the library will choose a random name), nor do you need to specify the -setcookie part.

I tested by just running
% erl -name foo -setcookie bar
in one shell, then ran
% ./entop foo@long.name bar

Or by running
% erl -sname foo -setcookie bar
in one shell and
% ./entop foo@short bar

(long.name and short are your long and short hostnames).

I also linked cecho and entop into my erlang libs dir, copied the entop bash script into my path and did the same tests. 

Let me know if it works for you.

**Comment by mazenharake** [comment]
I'm currently on vacation. I'll let you know as soon as I'm back and have
tested it.

**Comment by djnym** [comment]
Just a ping @mazenharake in case you are back from vacation.

**Comment by mazenharake** [comment]
@djnym I'm back! Sorry for the delay. I'll get to it asap :+1:

**Comment by mazenharake** [comment]
@djnym Merged and tagged. Let me know if this works out for you.

**Pull request merged**
